### ISSUE TITLE
[QUESTION] Roadmap, plans to release a tensorflow 1.4/1.5 supported version? 

### ISSUE THREAD

**Issue by alecuba16** [ROCmSoftwarePlatform/tensorflow#22]
I'm just asking if it will be a version for tensorflow 1.5 since the supported version of keras for 1.3v is 2.0.6 which is quite old and in keras 2.1.x there are so many new features that are not present in previous versions.

**Comment by whchung** [comment]
Since we did the port of 1.0.1 back in October '17 we did quite a lot of improvements in ROCm stack so this port of 1.3.0 has a much simpler architecture, and shall allow supporting newer versions a simpler job. I'll introduce some changes to this repository next week so we can see port be made publicly.
