### ISSUE TITLE
Merge back upstream  ?

### ISSUE THREAD

**Issue by gsahbi** [ROCmSoftwarePlatform/tensorflow#37]
It's more of a question as to why you chose not to fork tensorflow repo and be able to pull back new features and bugfixes, I think they are at 1.7 release. Was it very tightly coupled to Cuda stuff ?

**Comment by gstoner** [comment]
When you start port you fork the release then merge the changes,  the reason we had not done so to date was we need to get list legal agreement ok by our Legal team.  it called Contributor Licence Agreement.   This now signed and we are working closely with Google/Tensorflow engineering team on the changes that needed to support a broader number of  Accelerators since there number of area that very CUDA specific in the Tensorflow codebase and starting to upstream the code.
