### ISSUE TITLE
Keras ResNet50 crashing on tensorflow

### ISSUE THREAD

**Issue by araina2** [ROCmSoftwarePlatform/tensorflow#46]
Steps to replicate the issue:
1.	Build the ROCM stack from here: https://github.com/RadeonOpenCompute/ROCm-docker/blob/master/quick-start.md
2.	docker pull rocm/tensorflow  (default tag: latest)
3.	sudo docker run -it --device=/dev/kfd --device=/dev/dri --group-add video rocm/tensorflow
4.	In the bash login prompt of docker, do 
python tf-resnet50.py (code is below)
5.	The error should look like this:
InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'bn_conv1/keras_learning_phase' with dtype bool
         [[Node: bn_conv1/keras_learning_phase = Placeholder[dtype=DT_BOOL, shape=<unknown>, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Here is my entire code:
`import os
import tensorflow as tf
import numpy as np
from io import BytesIO
import time
from keras import backend as K
K.set_learning_phase(1) #set learning phase

img = np.ones((1, 224, 224, 3), dtype=np.float32)
input_img = tf.placeholder(tf.float32, (1, 224, 224, 3), name='input_img')
resnet50 = tf.contrib.keras.applications.ResNet50(weights='imagenet', include_top=True)
output = resnet50(input_img)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    num_iters = 30
    start = time.time()
    for _ in range(num_iters):
        output_val = sess.run(output,  feed_dict={input_img: img})
    end = time.time()
    time_taken = (end - start)/(float)(num_iters)
    print("The time taken by the kernel is %f" % time_taken)`

**Comment by 7SK** [comment]
Hi @araina2 , please use keras from tf for setting learning phase as well. I mean use
"tf.contrib.keras.backend.set_learning_phase(True)"
instead of
"from keras import backend as K
K.set_learning_phase(1)"
you were using model from tf.contrib.keras but the learning_phase was set for keras you installed using pip
Hi @whchung , since some keras user prefer integer value over Boolean for learning_phase I created a pull request for it.  https://github.com/ROCmSoftwarePlatform/tensorflow/pull/47
