### ISSUE TITLE
Lack of supported GPU list.

### ISSUE THREAD

**Issue by isaac-rstor** [ROCmSoftwarePlatform/tensorflow#55]
ROCm correctly installs on Hawaii GPUs, but when I try to use hiptensorflow, I get the following error, and based on runtime it seems to fall back onto cpu:

`Ignoring visible gpu device (device: 0, name: Device 67a1, pci bus id: 0000:04:00.0) with AMDGPU ISA gfx701. The minimum required AMDGPU ISA is gfx803.`

This would have been nice to know before purchasing the Hawaii GPUs, because there was otherwise no indication that tensorflow would not support this GPU chipset.

Can we get an official list of supported GPUs specifically for the tensorflow package?

**Comment by sunway513** [comment]
Hi @isaac-rstor , please find the ROCm supported devices here:
https://rocm.github.io/hardware.html

**Comment by whchung** [comment]
/cc @gstoner for awareness.

@isaac-rstor I myself doesn't know the list of SKUs we support on ROCm. We use AMD GPU ISA version to tell if a GPU is supported. Currently gfx803 (Fiji-family) and gfx900 (Vega-family) are supported. Unfortunately gfx700 (Hawaii-family) is not supported.

https://github.com/ROCmSoftwarePlatform/tensorflow/blob/rocm-v1/tensorflow/core/common_runtime/gpu/gpu_device.cc#L749

You can tell your GPU ISA version from this command in your ROCm installation: `/opt/rocm/bin/rocminfo`

From TensorFlow perspective actually it's possible to make Hawaii `gfx700` be a supported target. Problem lies in supporting components such as `MIOpen` and `rocBLAS` which contain GPU kernels tailor-made for supported GPU families. Since Hawaii was released before official ROCm 1.0 release the team didn't put much emphasis supporting gfx700.

If you are determined to try this project on Hawaii, it's could still be possible, but does require some experiments:
- change the line mentioned above to cover `700`.
- rebuild TensorFlow from source.
- may need to change integration logic in `stream_executor/rocm` so we carefully pick supported algorithms in `MIOpen` and `rocBLAS`.

**Comment by isaac-rstor** [comment]
@sunway513 the list presented on this page may need updating if the s9100 line (and others) are not supported.  https://rocm.github.io/ROCmRadeonProcompare.html - and as I mentioned, the ROCm driver layer (and OpenCL) are working just fine.

@whchung Will do. Thanks for the tips.  I think I'll be able to get this working!
